### ISSUE TITLE
Reading continuous data with cbpy

### ISSUE THREAD

**Issue by jsv13** [dashesy/CereLink#88] opened 2018-05-12 07:38 UTC
I manage to retrieve events from nPlayServer with cbpy, but I cannot get continuous data. Streaming continuous data is on, e.g. I can get them via the cbSDK.
Can anyone provide an example showing how to get continuous data in cbpy?
thanks!

**Comment by cboulay** [comment] 2018-05-12 14:42
I wrote a convenience class for myself that wraps cbpy that I use in a few different applications.
You can see how I get continuous data [here](https://github.com/SachsLab/cerebuswrapper/blob/master/cerebuswrapper/cbsdkConnection.py#L130-L137).

**Comment by zeeMonkeez** [comment] 2018-05-14 19:20
@cboulay how do you match sample times between events and continuous data in this use case? `cbMex` returns a common time base, but it's not clear to me how `cbpy` might expose that...

**Comment by cboulay** [comment] 2018-05-14 21:45
@zeeMonkeez Hi Jonas. Sorry I can't look into it right now. (going to Asilomar? I am nowhere near ready)

Anyway, there's a recently contributed `get_data` function in the 7.0 branch [here](https://github.com/dashesy/CereLink/blob/CereLink7.0/cerebus/cbpy.pyx#L364-L379). This fetches events and continuous data together in one function after a reset. The timestamps of the events should be offset from the 0th sample of the continuous data.

I haven't had a need for this because my I'm either looking at these things independently, or I'm looking at them offline loaded from .nev/.nsx files, but I think that's going to change.

**Comment by zeeMonkeez** [comment] 2018-05-15 06:51
@cboulay Hey Chad, thanks I'll have a look. No, Asilomar didn't fit in my schedule. I'll be in Minneapolis in June, though, will you be there? Seems like you're up to doing some cool things, it'd be cool to chat...

**Comment by cboulay** [comment] 2018-11-12 20:42
@jsv13 Very late reply, but in case anyone else encounters this, I've noticed that channels coming from the Analog Inputs aren't replayed by nPlayServer.

**Comment by stinos** [comment] 2018-12-17 16:32
> I've noticed that channels coming from the Analog Inputs aren't replayed by nPlayServer.

According to Blackrock support this is a known bug in the current version 7, a fix is upcoming, and it should also not happen in nPlayServer versions 6.5.4 and below.

**Comment by cboulay** [comment] 2018-12-17 21:48
Closing. Use #97

**Closed by cboulay** 2018-12-17 21:48 UTC

**Comment by agamemnonc** [comment] 2019-07-19 10:41
I am also trying to read continuous data only using cbpy and have encountered the following issue.

I have a main program which queries the device for new data continuously (i.e., no sleep commands in-between). I have set the `continuous_length` in `buffer_parameter` to the desired samples I want to read per every read operation. 

```python
from cerebus import cbpy
samples_per_read = 100

buffer_parameter = {
    'double': True,
    'continuous_length': samples_per_read 
}
result, _ = cbpy.trial_config(
    reset=True,
    buffer_parameter=buffer_parameter)

def read():
    result, trial = cbpy.trial_continuous(reset=True)
    data = process(trial)
    return data
``` 

Now, ideally I would want to continuously read data in a loop, such that execution is blocked until the data become available, something like:
```python
while True:
   data = read()
```
Ideally, I would expect program execution to be blocked until data become available since `continuous_length` is set to the desired number of samples per read operation, but what I observe is that instead a smaller number of samples is read and after a little while when no samples are available to be read, an exception is raised. Is this expected behaviour? 

Alternatively, I could set the number of samples per read to 1 and internally check if the desired sampes have been read, but querying the device sample by sample sounds a bit like an overkill. 

Any ideas? Thanks.

**Comment by cboulay** [comment] 2019-07-19 13:27
It would be a non-trivial amount of work to add a timeout parameter to [SdkGetTrialData](https://github.com/dashesy/CereLink/blob/19302e6d1d7c2547000cdba152b197e9d69f123a/cbmex/cbsdk.cpp#L1793-L1821). It's tricky to do correctly and I don't have time for that right now.

The simplest solution is to buffer the data on the client side. Or, better yet, have your analysis pipeline be flexible to the number of samples it receives (ultimately that usually means buffering at some stage).

If you want to make an argument for a blocking call to fetch data or you want to propose a way to do that then please open a new issue.
